### PR TITLE
Change code snippet format

### PR DESCRIPTION
**Pull request by insukcho**
The current code snippet is a single line even there are 2 lines.
Also, want to make is like a code rather than normal text

### CODE REVIEW

**Comment by insukcho** [comment]
thanks for the guideline @JasonStoltz 
I've fixed as following your direction and committed it

**Comment by JasonStoltz** [comment]
@insukcho Thanks! One last thing, can you rebase from master? I just committed a fix that will pass those failing specs.

**Comment by insukcho** [comment]
@JasonStoltz 
I though it will be easy to rebase and merge to master w/ clicking button from here, but it seems I have no permission to do that. Should I fork the branch and rebase by using command and PR again?

**Comment by JasonStoltz** [comment]
@insukcho What you described should probably work:

You might also be able to use the following commands:

```
git fetch origin master
git rebase FETCH_HEAD
git push -f
```

**Comment by insukcho** [comment]
@JasonStoltz Sorry for the late response.

Honestly, I'm not familiar with rebase from the master and I'm not sure I understood your request, correctly.

Should I clone from `swiftype/swiftype-py` or `insukcho/swiftype-py`?

I've tried below steps, but no luck. Because I can see my commits from `insukcho/swiftype-py` but when I clone it, it is already up-to-date.

```
git clone https://github.com/insukcho/swiftype-py.git
cd swiftype-py/
git fetch origin master
git rebase FETCH_HEAD
git push -f
```

But when I tried to clone `swiftype/swiftype-py` I cannot see my branch and my commits, so not available to checkout my branch and rebase them to the master.

What did I miss here?

**Comment by JasonStoltz** [comment]
@insukcho Hey Chris, sorry for trying to make you jump through those hoops. I opened up a new PR with your changes and merged that https://github.com/swiftype/swiftype-py/pull/22.

Thank you for the contribution!

**Pull request closed without merging**
