### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by robgolding**
This PR updates the library to be compatible with both Python 2 and 3. It uses the `future` library to achieve that, though there weren't too many changes that were required.

The biggest change is that the `VCRpy` package was updated to the latest version, which necessitated migrating the cassettes to the new format. Tests now pass in all supported version of Python, though!

### CODE REVIEW

**Comment by christopherjwang** [comment]
Hey @robgolding. Sorry for the delays -- this just popped on my radar. I'll be taking a look at this shortly. Thank you for your contribution.

**Comment by robgolding** [comment]
Hey @christopherjwang—any progress on this? Thanks!

**Comment by rjauquet** [comment]
Hi @christopherjwang, wondering if we could get an update on py3 compatibility

**Comment by PCManticore** [comment]
Hey @tehsven :wave: ! When you get a chance, can you ping someone for reviewing this PR? We'll definitely appreciate getting this merged and released :)

**Comment by christopherjwang** [comment]
@PCManticore I take full responsibility for this falling through the cracks. I'm looking right now

**Review by christopherjwang — APPROVED** [review]
Looks awesome, thanks for your contribution. Not speaking for Swiftype/Elastic: I owe you all a beer or an equivalent if you find yourself in SF.

I'll look into bumping and releasing a new version, I'm not in charge of those credentials at the moment.

**Pull request merged**
